### ISSUE TITLE
profile edit UI improvement 

### ISSUE THREAD

**Issue by karinocheretny** [CS-444-nilsstreedain/classroom-polling#41]
when going to 'profile' and clicking 'edit' the current UI looks like:
<img width="906" alt="Screenshot 2023-11-26 170519" src="https://github.com/CS-461-nilsstreedain/classroom-polling/assets/102639509/18db79ac-12d6-4959-b933-2f4f68d040fe">

This is not readable and should be adjusted to be user-friendly. 
- The edit sections are: first name, last name, email, password, new password, and password again
<img width="445" alt="Screenshot 2023-11-26 170758" src="https://github.com/CS-461-nilsstreedain/classroom-polling/assets/102639509/166bf37c-9347-41b5-933e-9be02bad6378">

I think changing passwords should happen separately in a section such as "change password". 
Additionally, there should be a button 'cancel' if a user decides to change their mind while editing information.

**Comment by nilsstreedain** [comment]
Merged some initial fixes in #166, general design will get improved with the site redesign when we bring in standard styles, but it is actually usable now.
<img width="471" alt="image" src="https://github.com/CS-444-nilsstreedain/classroom-polling/assets/25465133/23e3b58f-af14-4c68-b7fa-2e4dd30277e5">
